name: imap2gmail
version: '1.0.1'
summary: Copy e-mails form IMAP to GMail
license: MIT
website: https://github.com/tingdahl/imap2gmail
description: |
  imap2gmail copies messages from an IMAP server to a GMail account using GMail's APIs
confinement: strict
base: core20
grade: stable

parts:
  imap2gmail:
    plugin: python
    source: https://github.com/tingdahl/imap2gmail.git
    stage-packages:
      - python-six

apps:
  imap2gmail:
    command: bin/imap2gmail
    plugs:
      - home
      - network
