name: imap2gmail
version: '1.0'
summary: IMAP2GMail
description: |
  Imap2GMail copies messages on an IMAP server to a GMail account
confinement: devmode
base: core20

parts:
  test-offlineimap-tingdahl:
    plugin: python
    source: https://github.com/tingdahl/imap2gmail.git
    stage-packages:
      - python-six

apps:
  test-offlineimap-tingdahl:
    command: bin/imap2gmail
