name: imap2gmail
version: '1.0.17'
summary: Copy e-mails from IMAP to GMail
license: MIT
website: https://github.com/tingdahl/imap2gmail
description: |
  imap2gmail copies messages from an IMAP server to a GMail account using GMail's APIs.
confinement: strict
base: core24
grade: stable

platforms:
  amd64:
  arm64:
  armhf:
  ppc64el:
  s390x:

parts:
  imap2gmail:
    plugin: python
    source: https://github.com/tingdahl/imap2gmail.git
    build-packages:
      - libffi-dev
    override-build: |
      craftctl default
      ${CRAFT_PART_INSTALL}/bin/python3 -m pip install pytest pytest-cov
      ${CRAFT_PART_INSTALL}/bin/python3 -m pytest ${CRAFT_PART_SRC}/tests/ -v

apps:
  imap2gmail:
    command: bin/imap2gmail
    plugs:
      - home
      - network
      - network-bind
